version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS
      - run: sudo -E make install
      - run: sudo -E pip install tox
      - run: sudo -E make test
      - run: sudo -E apt-get install devscripts dh-virtualenv build-essential
      - run: sudo wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
      - run: sudo dpkg -i python-support_1.0.15_all.deb
      - run: sudo -E make release
      - run: cp ../*.deb $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts